---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: app
    run_list:
    attributes:

  - name: web
    run_list:
    attributes:
